#!/usr/bin/env bash
set -x 

# install tools 

sudo yum -y install wget vim curl jq 

# for ubuntu APT visit apt.puppetlabs.com and browse for your release version && install server
sudo wget http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb 
sudo dpkg -i puppetlabs-release-pc1-xenial.deb 
sudo apt-get -y update
sudo apt-get -y install puppet-agent

