#!/usr/bin/env bash
set -x 

# install tools 
if ! rpm -qa | grep -q puppet-agent; then

  sudo yum -y install wget vim curl jq 
  
  # for centos RPM's visit yum.puppetlabs.com and browse for your RPM releast version && install server
  sudo rpm -ihv http://yum.puppetlabs.com/puppet-release-el-7.noarch.rpm
  sudo yum -y install puppet-agent 

fi

sudo echo ' 
# Add /opt/puppetlabs/bin to the path for sh compatible users

if ! echo $PATH | grep -q /opt/puppetlabs/bin ; then
  export PATH=$PATH:/opt/puppetlabs/bin
  export PATH=$PATH:/opt/puppetlabs/puppet/bin
fi

if ! echo $MANPATH | grep -q /opt/puppetlabs/puppet/share/man ; then
  export MANPATH=$MANPATH:/opt/puppetlabs/puppet/share/man
fi' | sudo tee /etc/profile.d/puppet-agent.sh

