#!/usr/bin/env bash
set -x 

# install check
if ! dpkg -l |grep -q puppet-agent; then
  # packages
  sudo apt-get -y install wget vim curl jq

  # disable secure_path in /etc/sudoers 
  sudo sed -i '/secure_path/s/^/#/g' /etc/sudoers
  # host info
  sudo hostnamectl set-hostname 'puppet-agent-ubuntu'
  sudo echo "192.168.33.10      puppetmaster "  | sudo tee -a /etc/hosts

  # for ubuntu APT visit apt.puppetlabs.com and browse for your release version && install server
  sudo wget http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb 
  sudo dpkg -i puppetlabs-release-pc1-xenial.deb 
  sudo apt-get -y update
  sudo apt-get -y install puppet-agent

  sudo echo '
  # Add /opt/puppetlabs/bin to the path for sh compatible users
  
  if ! echo $PATH | grep -q /opt/puppetlabs/bin ; then
    export PATH=$PATH:/opt/puppetlabs/bin
    export PATH=$PATH:/opt/puppetlabs/puppet/bin
  fi
  
  if ! echo $MANPATH | grep -q /opt/puppetlabs/puppet/share/man ; then
    export MANPATH=$MANPATH:/opt/puppetlabs/puppet/share/man
  fi' | sudo tee /etc/profile.d/puppet-agent.sh

  # add dns_alt_names to /etc/hosts must be approved in the masters puppet.conf under dns_alt_names in order to work properly 
  sudo grep -q -F '192.168.33.10  puppet puppetmaster puppetmaster.local puppetserver' /etc/hosts || sudo echo '192.168.33.10  puppet puppetmaster puppetmaster.local puppetserver' | sudo tee -a  /etc/hosts
fi
