#!/usr/bin/env bash
set -x 

# install check
if ! rpm -qa | grep -q puppet-agent; then
  # packages 
  sudo yum -y install wget vim curl jq 
 
  # disable "secure_path" in /etc/suoders
  sudo sed -i 's\Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin\#Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin\g' /etc/sudoers
  
  #host info
  sudo echo "192.168.33.10      puppetmaster "  | sudo tee -a /etc/hosts
  sudo hostnamectl set-hostname 'puppet-agent-centos'

  # for centos RPM's visit yum.puppetlabs.com and browse for your RPM releast version && install server
  sudo rpm -ihv http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
  sudo yum -y udpate
  sudo yum -y install puppet-agent 

  # add ./puppetlabs/puppet/bin to PATH
  sudo echo ' 
  # Add /opt/puppetlabs/bin to the path for sh compatible users
  
  if ! echo $PATH | grep -q /opt/puppetlabs/bin ; then
    export PATH=$PATH:/opt/puppetlabs/bin
    export PATH=$PATH:/opt/puppetlabs/puppet/bin
  fi
  
  if ! echo $MANPATH | grep -q /opt/puppetlabs/puppet/share/man ; then
    export MANPATH=$MANPATH:/opt/puppetlabs/puppet/share/man
  fi' | sudo tee /etc/profile.d/puppet-agent.sh
  
  # add dns_alt_names to /etc/hosts must be approved in the masters puppet.conf under dns_alt_names in order to work properly 
  sudo grep -q -F '192.168.33.10  puppet puppetmaster puppetmaster.local puppetserver' /etc/hosts || sudo echo '192.168.33.10  puppet puppetmaster puppetmaster.local puppetserver' | sudo tee -a  /etc/hosts
fi
